/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jEWS;

import java.io.BufferedReader;
import java.io.StringReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;

import jEWS.DialogKoKab;
import java.awt.Dialog;

import java.awt.image.BufferedImage;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.*;

import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.JDialog;
import javax.swing.JFrame;

import java.net.URL;
import java.net.URLConnection;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.Date;
import java.util.Formatter;
import java.util.Locale;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;

import javax.xml.parsers.*;
import javax.xml.xpath.XPathFactory;
import javax.xml.xpath.XPath;

import javax.imageio.ImageIO;

import org.xml.sax.InputSource;
import org.w3c.dom.*;

/**
 *
 * @auAuthor Renaldy
 */
public class javaEWS extends javax.swing.JFrame {

    /**
     * Creates new form javaEWS
     */
    public javaEWS() {
        
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/db_bmkg?user=root&password=skm2010");            
            RunEWS();
            t.start();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtWaktu = new javax.swing.JTextField();
        txtLatitude = new javax.swing.JTextField();
        txtLongitude = new javax.swing.JTextField();
        txtMagnitude = new javax.swing.JTextField();
        txtKedalaman = new javax.swing.JTextField();
        txtWilayah1 = new javax.swing.JTextField();
        txtWilayah2 = new javax.swing.JTextField();
        txtWilayah5 = new javax.swing.JTextField();
        txtWilayah3 = new javax.swing.JTextField();
        txtWilayah4 = new javax.swing.JTextField();
        txtPotensi = new javax.swing.JTextField();
        txtKab1 = new javax.swing.JTextField();
        btnWil1 = new javax.swing.JButton();
        txtKab2 = new javax.swing.JTextField();
        txtKab3 = new javax.swing.JTextField();
        txtKab4 = new javax.swing.JTextField();
        txtKab5 = new javax.swing.JTextField();
        btnWil2 = new javax.swing.JButton();
        btnWil3 = new javax.swing.JButton();
        btnWil4 = new javax.swing.JButton();
        btnWil5 = new javax.swing.JButton();
        txtKodeKokab2 = new javax.swing.JTextField();
        txtKodeKokab3 = new javax.swing.JTextField();
        txtKodeKokab4 = new javax.swing.JTextField();
        txtKodeKokab5 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblPic = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtKodeKokab1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbStatus1 = new javax.swing.JComboBox();
        cbStatus2 = new javax.swing.JComboBox();
        cbStatus3 = new javax.swing.JComboBox();
        cbStatus4 = new javax.swing.JComboBox();
        cbStatus5 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Early Warning Message");
        setPreferredSize(new java.awt.Dimension(950, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Latitude :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 69, 100, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Waktu :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 41, 100, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Longitude :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 97, 100, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Magnitude :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 125, 100, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Kedalaman :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 153, 100, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Kabupaten/Kota - Provinsi");
        jLabel6.setAlignmentY(0.0F);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jLabel7.setText("Wilayah 2 :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 25));

        jLabel8.setText("Wilayah 3 :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 25));

        jLabel9.setText("Wilayah 4 :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 25));

        jLabel10.setText("Wilayah 5 :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 25));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Potensi :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 181, 100, -1));

        txtWaktu.setEditable(false);
        txtWaktu.setToolTipText("");
        txtWaktu.setName(""); // NOI18N
        getContentPane().add(txtWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 38, 159, 25));

        txtLatitude.setEditable(false);
        txtLatitude.setName(""); // NOI18N
        getContentPane().add(txtLatitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 66, 61, 25));

        txtLongitude.setEditable(false);
        txtLongitude.setName(""); // NOI18N
        getContentPane().add(txtLongitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 94, 61, 25));

        txtMagnitude.setEditable(false);
        txtMagnitude.setName(""); // NOI18N
        getContentPane().add(txtMagnitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 122, 61, 25));

        txtKedalaman.setEditable(false);
        txtKedalaman.setName(""); // NOI18N
        getContentPane().add(txtKedalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 61, 25));

        txtWilayah1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtWilayah1.setName(""); // NOI18N
        getContentPane().add(txtWilayah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 296, 25));

        txtWilayah2.setName(""); // NOI18N
        getContentPane().add(txtWilayah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 296, 25));

        txtWilayah5.setName(""); // NOI18N
        getContentPane().add(txtWilayah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 296, 25));

        txtWilayah3.setName(""); // NOI18N
        getContentPane().add(txtWilayah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 296, 25));

        txtWilayah4.setName(""); // NOI18N
        getContentPane().add(txtWilayah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 296, 25));

        txtPotensi.setEditable(false);
        txtPotensi.setName(""); // NOI18N
        getContentPane().add(txtPotensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 178, 350, 25));

        txtKab1.setName(""); // NOI18N
        getContentPane().add(txtKab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 280, 25));

        btnWil1.setText("jButton1");
        btnWil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWil1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnWil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 330, 35, 25));

        txtKab2.setName(""); // NOI18N
        getContentPane().add(txtKab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 280, 25));

        txtKab3.setName(""); // NOI18N
        getContentPane().add(txtKab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 280, 25));

        txtKab4.setName(""); // NOI18N
        getContentPane().add(txtKab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 280, 25));

        txtKab5.setName(""); // NOI18N
        getContentPane().add(txtKab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 280, 25));

        btnWil2.setText("jButton1");
        btnWil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWil2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnWil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 360, 35, 25));

        btnWil3.setText("jButton1");
        btnWil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWil3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnWil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 390, 35, 25));

        btnWil4.setText("jButton1");
        btnWil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWil4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnWil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 420, 35, 25));

        btnWil5.setText("jButton1");
        btnWil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWil5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnWil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 450, 35, 25));

        txtKodeKokab2.setName(""); // NOI18N
        getContentPane().add(txtKodeKokab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 360, 70, 25));

        txtKodeKokab3.setName(""); // NOI18N
        getContentPane().add(txtKodeKokab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 390, 70, 25));

        txtKodeKokab4.setName(""); // NOI18N
        getContentPane().add(txtKodeKokab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 420, 70, 25));

        txtKodeKokab5.setName(""); // NOI18N
        getContentPane().add(txtKodeKokab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 450, 70, 25));

        btnSave.setText("SIMPAN");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 90, 30));

        lblPic.setToolTipText("");
        getContentPane().add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 250));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Wilayah 1 :");
        jLabel13.setAlignmentY(0.0F);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 25));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Status");
        jLabel14.setToolTipText("");
        jLabel14.setAlignmentY(0.0F);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 90, -1));
        jLabel14.getAccessibleContext().setAccessibleName("Kode Wilayah");

        txtKodeKokab1.setName(""); // NOI18N
        getContentPane().add(txtKodeKokab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 330, 70, 25));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Wilayah");
        jLabel15.setAlignmentY(0.0F);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Kode Wilayah");
        jLabel16.setToolTipText("");
        jLabel16.setAlignmentY(0.0F);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 310, 76, -1));

        cbStatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AWAS", "WASPADA", "SIAGA" }));
        getContentPane().add(cbStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 90, 25));

        cbStatus2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AWAS", "WASPADA", "SIAGA" }));
        getContentPane().add(cbStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 90, 25));

        cbStatus3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AWAS", "WASPADA", "SIAGA" }));
        getContentPane().add(cbStatus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 90, 25));

        cbStatus4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AWAS", "WASPADA", "SIAGA" }));
        getContentPane().add(cbStatus4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 90, 25));

        cbStatus5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AWAS", "WASPADA", "SIAGA" }));
        getContentPane().add(cbStatus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, 90, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnWil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWil1ActionPerformed
        // TODO add your handling code here:
        //JDialog addHoseD = new ListKoKab(this,true);  
        JDialog addHoseD = new DialogKoKab(this,true);  
        //addHoseD.pack();
        addHoseD.setLocationRelativeTo(null);
        addHoseD.setVisible(true);
        String result[] = DialogKoKab.AmbilNilai();
        this.txtKodeKokab1.setText(result[0]);
        this.txtKab1.setText(result[1] + " -- " + result[2]);
        
    }//GEN-LAST:event_btnWil1ActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String reportDate = "";
        try {
            Date myDate = new SimpleDateFormat("dd-MMM-yy H:mm:ss", Locale.ENGLISH).parse(this.txtWaktu.getText().substring(0, 18));
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd H:mm:ss");
            reportDate = df.format(myDate);            
        } catch (Exception e) {
        }
        
        String Sql = "";
        Sql = "UPDATE tbl_gempa SET " +
                      "kode_kokab1 = '" + this.txtKodeKokab1.getText() + "', " +
                      "kode_kokab2 = '" + this.txtKodeKokab2.getText() + "', " +
                      "kode_kokab3 = '" + this.txtKodeKokab3.getText() + "', " +
                      "kode_kokab4 = '" + this.txtKodeKokab4.getText() + "', " +
                      "kode_kokab5 = '" + this.txtKodeKokab5.getText() + "', " +
                      "status1 = '" + this.cbStatus1.getSelectedIndex() + "', " +
                      "status2 = '" + this.cbStatus2.getSelectedIndex() + "', " +
                      "status3 = '" + this.cbStatus3.getSelectedIndex() + "', " +
                      "status4 = '" + this.cbStatus4.getSelectedIndex() + "', " +
                      "status5 = '" + this.cbStatus5.getSelectedIndex() + "' " +
              "WHERE waktu_gempa = '" + reportDate + "'" ;
        try {
            System.out.println(Sql);
            Statement st = connect.createStatement();
            int i = st.executeUpdate(Sql); 
        } catch (Exception e) {
        }        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnWil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWil2ActionPerformed
        JDialog addHoseD = new DialogKoKab(this,true);  
        //addHoseD.pack();
        addHoseD.setLocationRelativeTo(null);
        addHoseD.setVisible(true);
        String result[] = DialogKoKab.AmbilNilai();
        this.txtKodeKokab2.setText(result[0]);
        this.txtKab2.setText(result[1] + " -- " + result[2]);
    }//GEN-LAST:event_btnWil2ActionPerformed

    private void btnWil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWil3ActionPerformed
        JDialog addHoseD = new DialogKoKab(this,true);  
        //addHoseD.pack();
        addHoseD.setLocationRelativeTo(null);
        addHoseD.setVisible(true);
        String result[] = DialogKoKab.AmbilNilai();
        this.txtKodeKokab3.setText(result[0]);
        this.txtKab3.setText(result[1] + " -- " + result[2]);
    }//GEN-LAST:event_btnWil3ActionPerformed

    private void btnWil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWil4ActionPerformed
        JDialog addHoseD = new DialogKoKab(this,true);  
        //addHoseD.pack();
        addHoseD.setLocationRelativeTo(null);
        addHoseD.setVisible(true);
        String result[] = DialogKoKab.AmbilNilai();
        this.txtKodeKokab4.setText(result[0]);
        this.txtKab4.setText(result[1] + " -- " + result[2]);        // TODO add your handling code here:
    }//GEN-LAST:event_btnWil4ActionPerformed

    private void btnWil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWil5ActionPerformed
        JDialog addHoseD = new DialogKoKab(this,true);  
        //addHoseD.pack();
        addHoseD.setLocationRelativeTo(null);
        addHoseD.setVisible(true);
        String result[] = DialogKoKab.AmbilNilai();
        this.txtKodeKokab5.setText(result[0]);
        this.txtKab5.setText(result[1] + " -- " + result[2]);        // TODO add your handling code here:
    }//GEN-LAST:event_btnWil5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(javaEWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(javaEWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(javaEWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(javaEWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new javaEWS().setVisible(true);
            }
        });
    }
    
    private void RunEWS() {
        
            ShowImage("http://data.bmkg.go.id/eqmap.gif");        
            
            String myGempaXML = GetXML("http://data.bmkg.go.id/autogempa.xml");
            String[] myValue = new String[32];          
            myValue = ParseGempaXML(myGempaXML);
            ProcessEQ(myValue);
    }
    
    private Timer t = new javax.swing.Timer(60000, new ActionListener() {
          public void actionPerformed(ActionEvent e) {
               RunEWS();
          }
    });
    
    private void ShowImage (String myURL) {
        
        URL imageURL = null;
        BufferedImage bufImg = null;
        
        try {
            imageURL = new URL(myURL);
            bufImg = ImageIO.read(imageURL);
            BufferedImage resizedImage=resize(bufImg,lblPic.getWidth(),lblPic.getHeight());
            ImageIcon icon = new ImageIcon(resizedImage);
            lblPic.setIcon(icon);
        } catch (Exception e) {
        }
    }
    
    public static BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
    private void SetTextBox (String myValue[]) {
        
        String[] kokab = new String[3];
        
        this.txtWaktu.setText(myValue[0] + myValue[1]);
        this.txtLatitude.setText(myValue[2]);
        this.txtLongitude.setText(myValue[3]);
        this.txtMagnitude.setText(myValue[4]);
        this.txtKedalaman.setText(myValue[5]);
        this.txtPotensi.setText(myValue[11]);

        this.txtWilayah1.setText(myValue[6]);
        if (myValue[12]==null) {
            kokab = GetKOKAB(myValue[6]);
            this.txtKab1.setText(kokab[1] + " - " + kokab[2]);
            this.txtKodeKokab1.setText(kokab[0]);
        } else {
            this.txtKab1.setText(myValue[17] + " - " + myValue[22]);
            this.txtKodeKokab1.setText(myValue[12]);
        }
        
        this.txtWilayah2.setText(myValue[7]);
        if (myValue[13]==null) {
            kokab = GetKOKAB(myValue[7]);
            this.txtKab2.setText(kokab[1] + " - " + kokab[2]);
            this.txtKodeKokab2.setText(kokab[0]);
        } else {
            this.txtKab2.setText(myValue[18] + " - " + myValue[23]);
            this.txtKodeKokab2.setText(myValue[13]);
        }
        
        this.txtWilayah3.setText(myValue[8]);
        if (myValue[14]==null) {
            kokab = GetKOKAB(myValue[8]);
            this.txtKab3.setText(kokab[1] + " - " + kokab[2]);
            this.txtKodeKokab3.setText(kokab[0]);
        } else {
            this.txtKab3.setText(myValue[19] + " - " + myValue[24]);
            this.txtKodeKokab3.setText(myValue[14]);
        }
        
        this.txtWilayah4.setText(myValue[9]);  
        if (myValue[15]==null) {
            kokab = GetKOKAB(myValue[9]);
            this.txtKab4.setText(kokab[1] + " - " + kokab[2]);
            this.txtKodeKokab4.setText(kokab[0]);
        } else {
            this.txtKab4.setText(myValue[20] + " - " + myValue[25]);
            this.txtKodeKokab4.setText(myValue[15]);
        }
        
        this.txtWilayah5.setText(myValue[10]);
        if (myValue[16]==null) {
            kokab = GetKOKAB(myValue[10]);
            this.txtKab5.setText(kokab[1] + " - " + kokab[2]);
            this.txtKodeKokab5.setText(kokab[0]);
        } else {
            this.txtKab5.setText(myValue[21] + " - " + myValue[26]);
            this.txtKodeKokab5.setText(myValue[16]);
        }
        
        if (myValue[27] == null) {
        } else {
            System.out.println("rrrr " + myValue[27]);
            try {
                this.cbStatus1.setSelectedIndex(Integer.valueOf(myValue[27]));
            } catch (Exception e) {
                System.out.println("Line 432: " + e.getMessage());
            }            
        }
        
        if (myValue[28] == null) {
        } else {
            try {
                this.cbStatus2.setSelectedIndex(Integer.valueOf(myValue[28]));
            } catch (Exception e) {
                System.out.println("Line 491: " + e.getMessage());
            }            
        }
        
        if (myValue[29] == null) {
        } else {
            try {
                this.cbStatus3.setSelectedIndex(Integer.valueOf(myValue[29]));
            } catch (Exception e) {
                System.out.println("Line 500: " + e.getMessage());
            }            
        }
        
        if (myValue[30] == null) {
        } else {
            try {
                this.cbStatus4.setSelectedIndex(Integer.valueOf(myValue[30]));
            } catch (Exception e) {
                System.out.println("Line 509: " + e.getMessage());
            }            
        }
        
        if (myValue[31] == null) {
        } else {
            try {
                this.cbStatus5.setSelectedIndex(Integer.valueOf(myValue[31]));
            } catch (Exception e) {
                System.out.println("Line 518: " + e.getMessage());
            }            
        }
        
    }
    
    private String[] GetKOKAB (String strWil) {
              
        String[] kokab = new String[3];
       
        String[] arrWil = strWil.split(" ");
        String myWil = arrWil[3];

        try {
            
            Statement st = connect.createStatement();
            String sql="";

            // CARI wilayah pada list yang sudah terdaftar 
            sql = " SELECT wilayah, tbl_map_wilayah.kode_kokab, kokab, provinsi " +
                  " FROM tbl_map_wilayah " +
                  "     INNER JOIN tbl_mstr_kokab ON tbl_map_wilayah.kode_kokab = tbl_mstr_kokab.kode_kokab " +
                  " WHERE wilayah LIKE '" + myWil + "'";                          
            ResultSet rs = st.executeQuery(sql);
            if (rs.first()){
               kokab[0] = rs.getString("kode_kokab");
               kokab[1] = rs.getString("kokab");
               kokab[2] = rs.getString("provinsi");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        return kokab;
    }
    
    private String GetXML (String UrlStr) {
 
        try {
                        
            URL url = new URL(UrlStr);    
            URLConnection conn = url.openConnection();
            conn.setDoOutput(true);
            conn.connect(); 
                            
            //--- membaca response
            InputStreamReader isr = new InputStreamReader(conn.getInputStream());
            BufferedReader in = new BufferedReader(isr);
            String decodedString;
            String xml = ""; //"<resp><status>good</status><msg>hi</msg></resp>";
            while ((decodedString = in.readLine()) != null) {
                //System.out.println(decodedString);
                xml = xml + decodedString;
            }
            in.close();
            System.out.println(xml);
            return xml;    
            
        } catch (Exception e) {
            System.out.println("fachri error : ");
            return "";
        }
    }
    
    private static String[] ParseGempaXML (String xml) {
        
        InputSource source = new InputSource(new StringReader(xml));

        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        DocumentBuilder db = null;
        try {
            db = dbf.newDocumentBuilder();
        } catch (Exception e) {
            
        }

        Document document = null;
        try {
            document= db.parse(source);
        } catch (Exception e) {

        }

        XPathFactory xpathFactory;
        xpathFactory = XPathFactory.newInstance();
        XPath xpath = xpathFactory.newXPath();

        String waktu, tanggal, jam, zona, lati, longi, magni, deep, wil1, wil2, wil3, wil4, wil5, potensi;
        waktu=""; tanggal=""; jam=""; zona="";lati=""; longi=""; magni=""; deep=""; wil1=""; wil2=""; wil3=""; wil4=""; wil5=""; potensi="";
        
        String myValue[] = new String[32];
        
        try {
            tanggal = xpath.evaluate("/Infogempa/gempa/Tanggal", document);
            jam = xpath.evaluate("/Infogempa/gempa/Jam", document);
            zona = jam.substring(9);
            jam = jam.substring(0,9);
            waktu = tanggal + " " + jam;
            myValue[0] = waktu;
            myValue[1] = zona;
            System.out.println("Waktu = " + waktu + " " + " " + zona);
            String[] coordinate = xpath.evaluate("/Infogempa/gempa/point/coordinates", document).split(",");
            longi = coordinate[0];
            lati = coordinate[1];
            myValue[2] = lati;
            myValue[3] = longi;
            System.out.println("Latitude = " + lati + "       Longitude = " + longi);
            magni = xpath.evaluate("/Infogempa/gempa/Magnitude", document);
            deep = xpath.evaluate("/Infogempa/gempa/Kedalaman", document);
            myValue[4] = magni;
            myValue[5] = deep;
            System.out.println("Kekuatan = " + magni + "       Kedalaman = " + deep);
            wil1 = xpath.evaluate("/Infogempa/gempa/Wilayah1", document);
            myValue[6] = wil1;
            System.out.println("Wilayah 1 = " + wil1);
            wil2 = xpath.evaluate("/Infogempa/gempa/Wilayah2", document);
            myValue[7] = wil2;
            System.out.println("Wilayah 2 = " + wil2);
            wil3 = xpath.evaluate("/Infogempa/gempa/Wilayah3", document);
            myValue[8] = wil3;
            System.out.println("Wilayah 3 = " + wil3);
            wil4 = xpath.evaluate("/Infogempa/gempa/Wilayah4", document);
            myValue[9] = wil4;
            System.out.println("Wilayah 4 = " + wil4);
            wil5 = xpath.evaluate("/Infogempa/gempa/Wilayah5", document);                
            myValue[10] = wil5;
            System.out.println("Wilayah 5 = " + wil5);
            potensi = xpath.evaluate("/Infogempa/gempa/Potensi", document);
            myValue[11] = potensi;
            System.out.println("Potensi = " + potensi);            
        } catch (Exception ex) {
        
        }

        return myValue;
    }
    
    private void ProcessEQ(String[] myValue) {
        
        //INSERT INTO DATABASE

        //Connection connect = null;

        try {

/*            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/db_bmkg?"
                + "user=root&password=MyP4ssword");
*/
            Statement st = connect.createStatement();
            String sql="";

            Date myDate = new SimpleDateFormat("dd-MMM-yy H:mm:ss", Locale.ENGLISH).parse(myValue[0]);
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd H:mm:ss");
            String reportDate = df.format(myDate);
            
            sql = ("SELECT gempa_seq FROM tbl_gempa WHERE waktu_gempa = '" + reportDate + "' AND zona LIKE '" + myValue[1] + "'");
            ResultSet rs = st.executeQuery(sql);          
            
            if (!rs.first()){   
                // Klo gempa baru maka masukkan dalam DB dan tampilkan dlm form
                sql = "INSERT INTO tbl_gempa (waktu_gempa, zona, latitude, longitude, magnitude, kedalaman, " +
                              "wilayah1, wilayah2, wilayah3, wilayah4, wilayah5, potensi, inserted_date) " +
                      "VALUES ('" + reportDate + "', '" + myValue[1] + "', '" + myValue[2] + "', '" + myValue[3] + "', '" +
                                    myValue[4] + "', '" + myValue[5] + "', '" + myValue[6] + "', '" + myValue[7] + "', '" +
                                    myValue[8] + "', '" + myValue[9] + "', '" + myValue[10] + "', '" + myValue[11] + "', now())";
                int i = st.executeUpdate(sql);  
                SetTextBox(myValue);
                              
            } else {
                // klo gempa lama maka ambil data dari DB trus tampilkan dalam form
                
                Statement st1 = connect.createStatement();
                sql = ("SELECT gm.*, kk1.kokab AS kokab1, kk1.provinsi AS provinsi1, kk2.kokab AS kokab2, kk2.provinsi AS provinsi2, " +
                             " kk3.kokab AS kokab3, kk3.provinsi AS provinsi3, kk4.kokab AS kokab4, kk4.provinsi AS provinsi4, " +
                             " kk5.kokab AS kokab5, kk5.provinsi AS provinsi5 " +
                       "FROM tbl_gempa AS gm " +
                       "LEFT JOIN tbl_mstr_kokab AS kk1 ON gm.kode_kokab1 = kk1.kode_kokab " +
                       "LEFT JOIN tbl_mstr_kokab AS kk2 ON gm.kode_kokab2 = kk2.kode_kokab " +
                       "LEFT JOIN tbl_mstr_kokab AS kk3 ON kk3.kode_kokab = gm.kode_kokab3 " +
                       "LEFT JOIN tbl_mstr_kokab AS kk4 ON kk4.kode_kokab = gm.kode_kokab4 " +
                       "LEFT JOIN tbl_mstr_kokab AS kk5 ON kk5.kode_kokab = gm.kode_kokab5 " +
                       "WHERE gempa_seq = " + rs.getString("gempa_seq"));    
                System.out.println(sql);
                ResultSet rs1 = st1.executeQuery(sql);    
                if (rs1.first()){ 
                    myValue[12] = rs1.getString("kode_kokab1");
                    myValue[13] = rs1.getString("kode_kokab2");
                    myValue[14] = rs1.getString("kode_kokab3");
                    myValue[15] = rs1.getString("kode_kokab4");
                    myValue[16] = rs1.getString("kode_kokab5");
                    myValue[17] = rs1.getString("kokab1");
                    myValue[18] = rs1.getString("kokab2");
                    myValue[19] = rs1.getString("kokab3");
                    myValue[20] = rs1.getString("kokab4");
                    myValue[21] = rs1.getString("kokab5");
                    myValue[22] = rs1.getString("provinsi1");
                    myValue[23] = rs1.getString("provinsi2");
                    myValue[24] = rs1.getString("provinsi3");
                    myValue[25] = rs1.getString("provinsi4");
                    myValue[26] = rs1.getString("provinsi5");
                    myValue[27] = rs1.getString("status1");
                    myValue[28] = rs1.getString("status2");
                    myValue[29] = rs1.getString("status3");
                    myValue[30] = rs1.getString("status4");
                    myValue[31] = rs1.getString("status5");
                }
                SetTextBox(myValue);
                rs1.close();
            }
            rs.close();
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    private Connection connect = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnWil1;
    private javax.swing.JButton btnWil2;
    private javax.swing.JButton btnWil3;
    private javax.swing.JButton btnWil4;
    private javax.swing.JButton btnWil5;
    private javax.swing.JComboBox cbStatus1;
    private javax.swing.JComboBox cbStatus2;
    private javax.swing.JComboBox cbStatus3;
    private javax.swing.JComboBox cbStatus4;
    private javax.swing.JComboBox cbStatus5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPic;
    private javax.swing.JTextField txtKab1;
    private javax.swing.JTextField txtKab2;
    private javax.swing.JTextField txtKab3;
    private javax.swing.JTextField txtKab4;
    private javax.swing.JTextField txtKab5;
    private javax.swing.JTextField txtKedalaman;
    public javax.swing.JTextField txtKodeKokab1;
    private javax.swing.JTextField txtKodeKokab2;
    private javax.swing.JTextField txtKodeKokab3;
    private javax.swing.JTextField txtKodeKokab4;
    private javax.swing.JTextField txtKodeKokab5;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtMagnitude;
    private javax.swing.JTextField txtPotensi;
    private javax.swing.JTextField txtWaktu;
    private javax.swing.JTextField txtWilayah1;
    private javax.swing.JTextField txtWilayah2;
    private javax.swing.JTextField txtWilayah3;
    private javax.swing.JTextField txtWilayah4;
    private javax.swing.JTextField txtWilayah5;
    // End of variables declaration//GEN-END:variables

}
